services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TRAW\NewsContentColumns\:
    resource: '../Classes/*'
    
  TRAW\NewsContentColumns\EventListener\News\NewsDetailActionEventListener:
    tags:
      - name: event.listener
        identifier: 'txnewscontentcolumns-detailaction'